POST http://localhost:5000/CreateAccount
Content-Type: application/json

{
  "ID":"jacking751",
  "PW":"123qwe"
}

###
POST http://localhost:5000/Login
Content-Type: application/json

{
  "ID":"jacking751",
  "PW":"123qwe"
}

###
POST http://localhost:5000/UserGameInfo
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken":"dvoxhy0zn5myyv9mm4ghws77u"
}

###
POST http://localhost:5000/FieldMonster
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken":"dvoxhy0zn5myyv9mm4ghws77u"
}

###
POST http://localhost:5000/Catch
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken":"dvoxhy0zn5myyv9mm4ghws77u",
  "MonsterID": 1
}

###
POST http://localhost:5000/DailyCheck
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken":"dvoxhy0zn5myyv9mm4ghws77u"
}