POST http://localhost:5000/CreateAccount
Content-Type: application/json

{
  "ID":"jacking751",
  "PW":"123qwe"
}

###
POST http://localhost:5000/Login
Content-Type: application/json

{
  "ID":"jacking751",
  "PW":"123qwe"
}

###
POST http://localhost:5000/UserGameInfo
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken":"6clbc9und2qtb2s26szhxxwwr"
}

###
POST http://localhost:5000/FieldMonster
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken":"6clbc9und2qtb2s26szhxxwwr"
}

###
POST http://localhost:5000/Catch
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken":"6clbc9und2qtb2s26szhxxwwr",
  "MonsterID": 1
}

###
POST http://localhost:5000/DailyCheck
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken":"6clbc9und2qtb2s26szhxxwwr"
}

###
POST http://localhost:5000/CheckPostmail
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken":"6clbc9und2qtb2s26szhxxwwr",
  "PageIndex": 0
}

###
POST http://localhost:5000/SendPostmail
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken":"6clbc9und2qtb2s26szhxxwwr",
  "StarCount": 999
}

###
POST http://localhost:5000/RecvPostmail
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken":"6clbc9und2qtb2s26szhxxwwr",
  "PostmailID": 3
}