POST http://localhost:5000/CreateAccount
Content-Type: application/json

{
  "ID":"jacking751",
  "PW":"123qwe"
}

###
POST http://localhost:5000/Login
Content-Type: application/json

{
  "ID":"jacking751",
  "PW":"123qwe"
}

###
POST http://localhost:5000/Login
Content-Type: application/json

{
  "ID":"richard0326",
  "PW":"1234"
}

###
POST http://localhost:5000/UserGameInfo
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken":"vhfg2vyxjr5f9yh6ba47j2ku0"
}

###
POST http://localhost:5000/FieldMonster
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken":"vhfg2vyxjr5f9yh6ba47j2ku0"
}

###
POST http://localhost:5000/Catch
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken": "vhfg2vyxjr5f9yh6ba47j2ku0",
  "MonsterID": 1
}

###
POST http://localhost:5000/DailyCheck
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken":"vhfg2vyxjr5f9yh6ba47j2ku0"
}

###
POST http://localhost:5000/CheckPostmail
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken":"vhfg2vyxjr5f9yh6ba47j2ku0",
  "PageIndex": 0
}

###
POST http://localhost:5000/CheckPostmail
Content-Type: application/json

{
  "ID":"richard0326",
  "AuthToken":"ybr4w44przs812oplsggu2s27",
  "PageIndex": 0
}

###
POST http://localhost:5000/SendPostmail
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken":"vhfg2vyxjr5f9yh6ba47j2ku0",
  "sendID":"richard0326",
  "StarCount": 900
}

###
POST http://localhost:5000/RecvPostmail
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken":"vhfg2vyxjr5f9yh6ba47j2ku0",
  "PostmailID": 4
}

###
POST http://localhost:5000/RankingInfo
Content-Type: application/json

{
  "ID":"jacking751",
  "AuthToken":"vhfg2vyxjr5f9yh6ba47j2ku0",
  "PageIndex": 0
}